### ISSUE TITLE
Objective-C version

### ISSUE THREAD

**Issue by Manueldjz** [ruipfcosta/RxMediaPicker#1]
there will be version for the objective C  ?

I have worked with UIImagePickerController

Thanks

**Comment by AndrewSB** [comment]
@Manueldjz I'm not sure if this makes sense for Objective C, since RxSwift isn't really built to suit Obj-C.

Maybe take a look at reactive cocoa, and their community libraries?

**Comment by freak4pc** [comment]
RxSwift is Swift only, so the picker is as well.
