### ISSUE TITLE
No edit photos will have a problem

### ISSUE THREAD

**Issue by astralchen** [ruipfcosta/RxMediaPicker#12]
func processPhoto(info: [String : AnyObject],
                      observer: AnyObserver<(UIImage, UIImage?)>) {
//        guard let image = info[UIImagePickerControllerOriginalImage] as? UIImage,
//              let editedImage = info[UIImagePickerControllerEditedImage] as? UIImage else {
//            observer.on(.error(RxMediaPickerError.generalError))
//            return
//        }
        
        let image = info[UIImagePickerControllerOriginalImage] as! UIImage
        let editedImage = info[UIImagePickerControllerEditedImage] as? UIImage

        observer.on(.next(image, editedImage))
        observer.on(.completed)
    }

**Comment by freak4pc** [comment]
Hey, mind providing a clear description of what you're expecting and what's not working for you?  @ilumanxi

**Comment by astralchen** [comment]
I just want to get a picture without editing, but always receive the error

**Comment by freak4pc** [comment]
@ilumanxi The PR referenced here will fix this.
As soon as it's approved by a reviewer I'll push a new minor version out :)

**Comment by freak4pc** [comment]
v1.1.0 has just been pushed on master. Updating to the latest CocoaPod resolves this. @ilumanxi
