### ISSUE TITLE
Error when picking photo with editable: false

### ISSUE THREAD

**Issue by adamsmaka** [ruipfcosta/RxMediaPicker#14]
Hi, when I use function picker.selectImage(editable: true) everything is fine
But when I change editable to false, then after picking a picture I got error
`Picker photo error: The operation couldn’t be completed. (RxMediaPicker.RxMediaPickerError error 0.)`
Why does this happen?

**Comment by freak4pc** [comment]
Are you using the latest version from Today (1.1.0) ? This sounds like a 1.0.0 issue that was just resolved today.
Make sure you `pod update` and verify. I'm using editable: false here with no issues.

<img width="729" alt="45ba5dd5-2c6f-415c-87e7-375836ad2920" src="https://cloud.githubusercontent.com/assets/605076/25717919/cadbb9b0-310c-11e7-9b43-f08fab3c47d9.png">

**Comment by adamsmaka** [comment]
<img width="306" alt="screen shot 2017-05-04 at 8 01 32 pm" src="https://cloud.githubusercontent.com/assets/22574704/25717964/97642610-3104-11e7-9ce1-976e7c79ec67.png">
What a quick answer! Of course now everything works fine! 😁 Thank you freak4pc!!!

**Comment by freak4pc** [comment]
My pleasure ;) @adamsmaka
