### ISSUE TITLE
How do I skip cropper screen? 

### ISSUE THREAD

**Issue by matghazaryan** [ruipfcosta/RxMediaPicker#16]
When i selected photo it asks me to crop photo. I want to skip that. How could I do that?

**Comment by freak4pc** [comment]
@pmbfish40 The default implementation sets `editable` to false, I don't think you should see the Crop screen. 

See here: https://github.com/RxSwiftCommunity/RxMediaPicker/blob/master/RxMediaPicker/RxMediaPicker.swift#L106

**Comment by matghazaryan** [comment]
wow thank you very much.
