### ISSUE TITLE
RxSwift 3.0 Compatibility

### ISSUE THREAD

**Issue by saru2020** [ruipfcosta/RxMediaPicker#7]
Hey,

I see that its dependent on 'RxSwift 2.0'.

Isn't this lib compatible with RxSwift 3.0?

**Comment by uknowmeright** [comment]
This is odd, going to have to ditch this framework now.. :(

**Comment by freak4pc** [comment]
Hey @saru2020 @uknowmeright 
I'll have a go at pushing a PR for this later tonight. Thanks for reporting :)

**Comment by AndrewSB** [comment]
Closed by #9

**Comment by freak4pc** [comment]
Hey all :-)

We have pushed a new v1.0.0 release but its not _yet_ on Cocoapods (gonna probably take an extra day to get the keys to push it) 

For now you can manually link to the repo by putting this in your Podfile:

`pod 'RxMediaPicker', :git => 'https://github.com/RxSwiftCommunity/RxMediaPicker.git', :branch => 'master'`

@uknowmeright @saru2020 

Cheers 🍺 
Shai

**Comment by freak4pc** [comment]
1.0.0 has been pushed up to Cocoapods !
